/* Ganti data contoh di file ini dengan data kelas yang sebenarnya. */
'use strict';

window.CLASS_PORTAL = {
  className: 'Kelas A — PGSD 2026',
  semester: 'Semester 1',
  academicYear: '2026/2027',
  semesterStart: '2026-08-26',
  groupLinks: [
    { label: 'Ilmu Pendidikan', platform: 'WhatsApp', url: 'https://chat.whatsapp.com/J4qI9KEeIrt1qxZwFI8msy', note: 'Grup diskusi mata kuliah.' },
    { label: 'Bilangan dan Pengolahan Data', platform: 'WhatsApp', url: 'https://chat.whatsapp.com/KPpdfYIAKMl51Cu7yMahNz', note: 'Grup diskusi mata kuliah.' },
    { label: 'Pendidikan Inklusif', platform: 'WhatsApp', url: 'https://chat.whatsapp.com/K9oabfLOzuc3MZhx2kzO5D', note: 'Grup diskusi mata kuliah.' },
    { label: 'Pendidikan Karakter', platform: 'WhatsApp', url: 'https://chat.whatsapp.com/K3EYpg3JTzTFz5aNtQDtNv?s=cl&p=a&mlu=0&ilr=0', note: 'Grup diskusi mata kuliah.' },
    { label: 'Psikologi Pendidikan', platform: 'WhatsApp', url: 'https://chat.whatsapp.com/DZkYQEEvyZrFONqwhNfp5N', note: 'Grup diskusi mata kuliah.' },
    { label: 'Kajian Kebahasaan', platform: 'WhatsApp', url: 'https://chat.whatsapp.com/L159hyNaCK06u9OqxlmAiS', note: 'Grup diskusi mata kuliah.' },
    { label: 'Konsep Dasar IPS SD', platform: 'WhatsApp', url: 'https://chat.whatsapp.com/HpkiCkDquM3LX311Eion58', note: 'Grup diskusi mata kuliah.' },
  ],
  courses: [
    {
      id: 'ilmu-pendidikan',
      name: 'Ilmu Pendidikan',
      lecturer: 'Dosen belum ditambahkan',
      schedule: 'Senin · 13.00–14.40 · 2 SKS · Ruang 02.02.01',
      classSchedule: { day: 'Senin', weekday: 1, start: '13:00', end: '14:40', sks: 2, room: '02.02.01' },
      groupLink: { platform: 'WhatsApp', url: 'https://chat.whatsapp.com/J4qI9KEeIrt1qxZwFI8msy', note: 'Grup diskusi mata kuliah.' },
      groups: [],
      tasks: [],
    },
    {
      id: 'bilangan-dan-pengolahan-data',
      name: 'Bilangan dan Pengolahan Data',
      lecturer: 'Dosen belum ditambahkan',
      schedule: 'Senin · 07.00–08.40 · 2 SKS · Ruang 02.01.03',
      classSchedule: { day: 'Senin', weekday: 1, start: '07:00', end: '08:40', sks: 2, room: '02.01.03' },
      groupLink: { platform: 'WhatsApp', url: 'https://chat.whatsapp.com/KPpdfYIAKMl51Cu7yMahNz', note: 'Grup diskusi mata kuliah.' },
      groups: [],
      tasks: [],
    },
    {
      id: 'pendidikan-inklusif',
      name: 'Pendidikan Inklusif',
      lecturer: 'Dosen belum ditambahkan',
      schedule: 'Senin · 08.40–10.20 · 2 SKS · Ruang 02.02.14',
      classSchedule: { day: 'Senin', weekday: 1, start: '08:40', end: '10:20', sks: 2, room: '02.02.14' },
      groupLink: { platform: 'WhatsApp', url: 'https://chat.whatsapp.com/K9oabfLOzuc3MZhx2kzO5D', note: 'Grup diskusi mata kuliah.' },
      groups: [],
      tasks: [],
    },
    {
      id: 'pendidikan-karakter',
      name: 'Pendidikan Karakter',
      lecturer: 'Dosen belum ditambahkan',
      schedule: 'Kamis · 09.30–12.00 · 3 SKS · Ruang 02.02.14',
      classSchedule: { day: 'Kamis', weekday: 4, start: '09:30', end: '12:00', sks: 3, room: '02.02.14' },
      groupLink: { platform: 'WhatsApp', url: 'https://chat.whatsapp.com/K3EYpg3JTzTFz5aNtQDtNv?s=cl&p=a&mlu=0&ilr=0', note: 'Grup diskusi mata kuliah.' },
      groups: [],
      tasks: [],
    },
    {
      id: 'psikologi-pendidikan',
      name: 'Psikologi Pendidikan',
      lecturer: 'Dosen belum ditambahkan',
      schedule: 'Selasa · 08.40–10.20 · 2 SKS · Ruang 02.02.13',
      classSchedule: { day: 'Selasa', weekday: 2, start: '08:40', end: '10:20', sks: 2, room: '02.02.13' },
      groupLink: { platform: 'WhatsApp', url: 'https://chat.whatsapp.com/DZkYQEEvyZrFONqwhNfp5N', note: 'Grup diskusi mata kuliah.' },
      groups: [],
      tasks: [],
    },
    {
      id: 'kajian-kebahasaan',
      name: 'Kajian Kebahasaan',
      lecturer: 'Dosen belum ditambahkan',
      schedule: 'Selasa · 10.20–12.00 · 2 SKS · Ruang 02.02.02',
      classSchedule: { day: 'Selasa', weekday: 2, start: '10:20', end: '12:00', sks: 2, room: '02.02.02' },
      groupLink: { platform: 'WhatsApp', url: 'https://chat.whatsapp.com/L159hyNaCK06u9OqxlmAiS', note: 'Grup diskusi mata kuliah.' },
      groups: [],
      tasks: [],
    },
    {
      id: 'konsep-dasar-ips-sd',
      name: 'Konsep Dasar IPS SD',
      lecturer: 'Dosen belum ditambahkan',
      schedule: 'Selasa · 13.50–16.20 · 3 SKS · Ruang 02.02.01',
      classSchedule: { day: 'Selasa', weekday: 2, start: '13:50', end: '16:20', sks: 3, room: '02.02.01' },
      groupLink: { platform: 'WhatsApp', url: 'https://chat.whatsapp.com/HpkiCkDquM3LX311Eion58', note: 'Grup diskusi mata kuliah.' },
      groups: [],
      tasks: [],
    },
  ],
};
